#!/usr/bin/env python3
"""Generate an importable JS data module for the calendar API."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

from calendar_data import (
    DEFAULT_DATA_PATH,
    MONTHS_AHEAD,
    ROOT,
    add_months,
    build_event_records,
    load_markets,
    parse_iso_date,
    public_market_records,
)


DEFAULT_OUTPUT = ROOT / "lib" / "calendar-data.js"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate lib/calendar-data.js")
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--start-date", help="Override generation start date, YYYY-MM-DD.")
    args = parser.parse_args()

    start = parse_iso_date(args.start_date)
    end = add_months(start, MONTHS_AHEAD)
    markets = load_markets(args.data)
    events = build_event_records(markets, start, end)
    payload = {
        "markets": public_market_records(markets),
        "events": events,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "calendarMeta": {
            "name": "大理赶集日历",
            "timezone": "Asia/Shanghai",
            "monthsAhead": MONTHS_AHEAD,
            "startDate": start.isoformat(),
            "endDate": end.isoformat(),
        },
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    json_text = json.dumps(payload, ensure_ascii=False, indent=2)
    args.output.write_text(
        "// Generated by scripts/generate_calendar_data.py. Do not edit by hand.\n"
        f"export const calendarData = {json_text};\n"
        "export default calendarData;\n",
        encoding="utf-8",
    )
    print(f"Generated {args.output} with {len(events)} events.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
